fragment HomeDataParts on HomeData {
  __typename
  _warning
  title
  createdAt
  updatedAt
  description
  hero_title
  hero_bg
  hero_text
  intro_title
  intro_text
  intro_offre
  offres {
    __typename
    title
    base_line
    text
    image {
      __typename
      src
      alt
    }
  }
  principe_title
  principe_sub_title
  principe_text
  principe_image {
    __typename
    src
    alt
  }
  principe_text_image
  principe_text_bt_label
  principe_text_bt_url
  testimonial {
    __typename
    text
    name
  }
  gallery {
    __typename
    src
    alt
  }
}

fragment TeamParts on Team {
  __typename
  _warning
  _team
  equipe {
    __typename
    title
    hero_title
    description
    hero_bg
  }
  _contact
  contact {
    __typename
    title
    hero_title
    description
    hero_bg
    before_text
    after_title
    after_text
  }
  members {
    __typename
    name
    published
    role
    education
    citation
    bio
    image_inactive
    image_active
    linkedin
    email
  }
}

fragment AssociateParts on Associate {
  __typename
  _warning
  title
  createdAt
  updatedAt
  description
  hero_title
  hero_bg
  intro
  associates {
    __typename
    name
    url
    published
    description
    image {
      __typename
      src
      alt
    }
  }
}

fragment PageParts on Page {
  __typename
  _warning
  title
  createdAt
  updatedAt
  description
  hero_title
  hero_bg
  useProse
  body
}

fragment NavDataPrimaryParts on NavDataPrimary {
  __typename
  _warning
  links {
    __typename
    name
    path
    title
    isButton
    target
    children {
      __typename
      name
      title
      isButton
      path
      target
    }
  }
}

fragment NavDataSecondaryParts on NavDataSecondary {
  __typename
  _warning
  links {
    __typename
    name
    path
    title
    isButton
    target
  }
}

fragment SiteDataParts on SiteData {
  __typename
  _warning
  _seo
  title
  description
  titleTemplate
  twitterUsername
  fbPageUrl
  image {
    __typename
    url
    alt
  }
  _footer
  informations
  networks {
    __typename
    url
    title
    icon
  }
}
