//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homeData: HomeData;
  homeDataConnection: HomeDataConnection;
  team: Team;
  teamConnection: TeamConnection;
  associate: Associate;
  associateConnection: AssociateConnection;
  page: Page;
  pageConnection: PageConnection;
  navDataPrimary: NavDataPrimary;
  navDataPrimaryConnection: NavDataPrimaryConnection;
  navDataSecondary: NavDataSecondary;
  navDataSecondaryConnection: NavDataSecondaryConnection;
  siteData: SiteData;
  siteDataConnection: SiteDataConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeDataArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeDataConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeDataFilter>;
};


export type QueryTeamArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
};


export type QueryAssociateArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAssociateConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AssociateFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryNavDataPrimaryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavDataPrimaryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavDataPrimaryFilter>;
};


export type QueryNavDataSecondaryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavDataSecondaryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavDataSecondaryFilter>;
};


export type QuerySiteDataArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteDataConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteDataFilter>;
};

export type DocumentFilter = {
  homeData?: InputMaybe<HomeDataFilter>;
  team?: InputMaybe<TeamFilter>;
  associate?: InputMaybe<AssociateFilter>;
  page?: InputMaybe<PageFilter>;
  navDataPrimary?: InputMaybe<NavDataPrimaryFilter>;
  navDataSecondary?: InputMaybe<NavDataSecondaryFilter>;
  siteData?: InputMaybe<SiteDataFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = HomeData | Team | Associate | Page | NavDataPrimary | NavDataSecondary | SiteData | Folder;

export type HomeDataOffresImage = {
  __typename?: 'HomeDataOffresImage';
  src: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type HomeDataOffres = {
  __typename?: 'HomeDataOffres';
  title?: Maybe<Scalars['String']['output']>;
  base_line?: Maybe<Scalars['String']['output']>;
  text?: Maybe<Scalars['String']['output']>;
  image?: Maybe<HomeDataOffresImage>;
};

export type HomeDataPrincipe_Image = {
  __typename?: 'HomeDataPrincipe_image';
  src: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type HomeDataTestimonial = {
  __typename?: 'HomeDataTestimonial';
  text?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
};

export type HomeDataGallery = {
  __typename?: 'HomeDataGallery';
  src: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type HomeData = Node & Document & {
  __typename?: 'HomeData';
  _warning?: Maybe<Scalars['String']['output']>;
  hero_text?: Maybe<Scalars['JSON']['output']>;
  intro_title?: Maybe<Scalars['String']['output']>;
  intro_text?: Maybe<Scalars['JSON']['output']>;
  intro_offre?: Maybe<Scalars['String']['output']>;
  offres?: Maybe<Array<Maybe<HomeDataOffres>>>;
  principe_title?: Maybe<Scalars['String']['output']>;
  principe_sub_title?: Maybe<Scalars['JSON']['output']>;
  principe_text?: Maybe<Scalars['JSON']['output']>;
  principe_image?: Maybe<HomeDataPrincipe_Image>;
  principe_text_image?: Maybe<Scalars['JSON']['output']>;
  principe_text_bt_label?: Maybe<Scalars['String']['output']>;
  principe_text_bt_url?: Maybe<Scalars['String']['output']>;
  testimonial?: Maybe<Array<Maybe<HomeDataTestimonial>>>;
  gallery?: Maybe<Array<Maybe<HomeDataGallery>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeDataOffresImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type HomeDataOffresFilter = {
  title?: InputMaybe<StringFilter>;
  base_line?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
  image?: InputMaybe<HomeDataOffresImageFilter>;
};

export type HomeDataPrincipe_ImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type HomeDataTestimonialFilter = {
  text?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
};

export type HomeDataGalleryFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type HomeDataFilter = {
  _warning?: InputMaybe<StringFilter>;
  hero_text?: InputMaybe<RichTextFilter>;
  intro_title?: InputMaybe<StringFilter>;
  intro_text?: InputMaybe<RichTextFilter>;
  intro_offre?: InputMaybe<StringFilter>;
  offres?: InputMaybe<HomeDataOffresFilter>;
  principe_title?: InputMaybe<StringFilter>;
  principe_sub_title?: InputMaybe<RichTextFilter>;
  principe_text?: InputMaybe<RichTextFilter>;
  principe_image?: InputMaybe<HomeDataPrincipe_ImageFilter>;
  principe_text_image?: InputMaybe<RichTextFilter>;
  principe_text_bt_label?: InputMaybe<StringFilter>;
  principe_text_bt_url?: InputMaybe<StringFilter>;
  testimonial?: InputMaybe<HomeDataTestimonialFilter>;
  gallery?: InputMaybe<HomeDataGalleryFilter>;
};

export type HomeDataConnectionEdges = {
  __typename?: 'HomeDataConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomeData>;
};

export type HomeDataConnection = Connection & {
  __typename?: 'HomeDataConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeDataConnectionEdges>>>;
};

export type TeamEquipe = {
  __typename?: 'TeamEquipe';
  title: Scalars['String']['output'];
  hero_bg: Scalars['String']['output'];
};

export type TeamContact = {
  __typename?: 'TeamContact';
  title: Scalars['String']['output'];
  hero_bg: Scalars['String']['output'];
  before_text?: Maybe<Scalars['String']['output']>;
  after_title?: Maybe<Scalars['String']['output']>;
  after_text?: Maybe<Scalars['String']['output']>;
};

export type TeamMembers = {
  __typename?: 'TeamMembers';
  name: Scalars['String']['output'];
  published: Scalars['Boolean']['output'];
  role: Scalars['String']['output'];
  education: Scalars['String']['output'];
  citation: Scalars['String']['output'];
  bio: Scalars['JSON']['output'];
  image_inactive: Scalars['String']['output'];
  image_active: Scalars['String']['output'];
  linkedin?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
};

export type Team = Node & Document & {
  __typename?: 'Team';
  _warning?: Maybe<Scalars['String']['output']>;
  _team?: Maybe<Scalars['String']['output']>;
  equipe?: Maybe<TeamEquipe>;
  _contact?: Maybe<Scalars['String']['output']>;
  contact?: Maybe<TeamContact>;
  members?: Maybe<Array<Maybe<TeamMembers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamEquipeFilter = {
  title?: InputMaybe<StringFilter>;
  hero_bg?: InputMaybe<ImageFilter>;
};

export type TeamContactFilter = {
  title?: InputMaybe<StringFilter>;
  hero_bg?: InputMaybe<ImageFilter>;
  before_text?: InputMaybe<StringFilter>;
  after_title?: InputMaybe<StringFilter>;
  after_text?: InputMaybe<StringFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type TeamMembersFilter = {
  name?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  role?: InputMaybe<StringFilter>;
  education?: InputMaybe<StringFilter>;
  citation?: InputMaybe<StringFilter>;
  bio?: InputMaybe<RichTextFilter>;
  image_inactive?: InputMaybe<ImageFilter>;
  image_active?: InputMaybe<ImageFilter>;
  linkedin?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
};

export type TeamFilter = {
  _warning?: InputMaybe<StringFilter>;
  _team?: InputMaybe<StringFilter>;
  equipe?: InputMaybe<TeamEquipeFilter>;
  _contact?: InputMaybe<StringFilter>;
  contact?: InputMaybe<TeamContactFilter>;
  members?: InputMaybe<TeamMembersFilter>;
};

export type TeamConnectionEdges = {
  __typename?: 'TeamConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Team>;
};

export type TeamConnection = Connection & {
  __typename?: 'TeamConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamConnectionEdges>>>;
};

export type AssociateAssociatesImage = {
  __typename?: 'AssociateAssociatesImage';
  src: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type AssociateAssociates = {
  __typename?: 'AssociateAssociates';
  name: Scalars['String']['output'];
  url?: Maybe<Scalars['String']['output']>;
  published: Scalars['Boolean']['output'];
  description: Scalars['JSON']['output'];
  image?: Maybe<AssociateAssociatesImage>;
};

export type Associate = Node & Document & {
  __typename?: 'Associate';
  _warning?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  hero_bg: Scalars['String']['output'];
  intro?: Maybe<Scalars['JSON']['output']>;
  associates?: Maybe<Array<Maybe<AssociateAssociates>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AssociateAssociatesImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type AssociateAssociatesFilter = {
  name?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  published?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<RichTextFilter>;
  image?: InputMaybe<AssociateAssociatesImageFilter>;
};

export type AssociateFilter = {
  _warning?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  hero_bg?: InputMaybe<ImageFilter>;
  intro?: InputMaybe<RichTextFilter>;
  associates?: InputMaybe<AssociateAssociatesFilter>;
};

export type AssociateConnectionEdges = {
  __typename?: 'AssociateConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Associate>;
};

export type AssociateConnection = Connection & {
  __typename?: 'AssociateConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AssociateConnectionEdges>>>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  _warning?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  hero_bg: Scalars['String']['output'];
  createdAt?: Maybe<Scalars['String']['output']>;
  updatedAt?: Maybe<Scalars['String']['output']>;
  description: Scalars['String']['output'];
  useProse?: Maybe<Scalars['Boolean']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageBodyPositionableImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  class?: InputMaybe<StringFilter>;
  position?: InputMaybe<StringFilter>;
  imgWidth?: InputMaybe<StringFilter>;
};

export type PageBodyFilter = {
  PositionableImage?: InputMaybe<PageBodyPositionableImageFilter>;
};

export type PageFilter = {
  _warning?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  hero_bg?: InputMaybe<ImageFilter>;
  createdAt?: InputMaybe<DatetimeFilter>;
  updatedAt?: InputMaybe<DatetimeFilter>;
  description?: InputMaybe<StringFilter>;
  useProse?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<PageBodyFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type NavDataPrimaryLinksChildren = {
  __typename?: 'NavDataPrimaryLinksChildren';
  name: Scalars['String']['output'];
  title: Scalars['String']['output'];
  isButton: Scalars['Boolean']['output'];
  path: Scalars['String']['output'];
  target: Scalars['String']['output'];
};

export type NavDataPrimaryLinks = {
  __typename?: 'NavDataPrimaryLinks';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
  title: Scalars['String']['output'];
  isButton: Scalars['Boolean']['output'];
  target: Scalars['String']['output'];
  children?: Maybe<Array<Maybe<NavDataPrimaryLinksChildren>>>;
};

export type NavDataPrimary = Node & Document & {
  __typename?: 'NavDataPrimary';
  _warning?: Maybe<Scalars['String']['output']>;
  links?: Maybe<Array<Maybe<NavDataPrimaryLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NavDataPrimaryLinksChildrenFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  isButton?: InputMaybe<BooleanFilter>;
  path?: InputMaybe<StringFilter>;
  target?: InputMaybe<StringFilter>;
};

export type NavDataPrimaryLinksFilter = {
  name?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  isButton?: InputMaybe<BooleanFilter>;
  target?: InputMaybe<StringFilter>;
  children?: InputMaybe<NavDataPrimaryLinksChildrenFilter>;
};

export type NavDataPrimaryFilter = {
  _warning?: InputMaybe<StringFilter>;
  links?: InputMaybe<NavDataPrimaryLinksFilter>;
};

export type NavDataPrimaryConnectionEdges = {
  __typename?: 'NavDataPrimaryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<NavDataPrimary>;
};

export type NavDataPrimaryConnection = Connection & {
  __typename?: 'NavDataPrimaryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NavDataPrimaryConnectionEdges>>>;
};

export type NavDataSecondaryLinks = {
  __typename?: 'NavDataSecondaryLinks';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
  title: Scalars['String']['output'];
  isButton: Scalars['Boolean']['output'];
  target: Scalars['String']['output'];
};

export type NavDataSecondary = Node & Document & {
  __typename?: 'NavDataSecondary';
  _warning?: Maybe<Scalars['String']['output']>;
  links?: Maybe<Array<Maybe<NavDataSecondaryLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NavDataSecondaryLinksFilter = {
  name?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  isButton?: InputMaybe<BooleanFilter>;
  target?: InputMaybe<StringFilter>;
};

export type NavDataSecondaryFilter = {
  _warning?: InputMaybe<StringFilter>;
  links?: InputMaybe<NavDataSecondaryLinksFilter>;
};

export type NavDataSecondaryConnectionEdges = {
  __typename?: 'NavDataSecondaryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<NavDataSecondary>;
};

export type NavDataSecondaryConnection = Connection & {
  __typename?: 'NavDataSecondaryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NavDataSecondaryConnectionEdges>>>;
};

export type SiteDataImage = {
  __typename?: 'SiteDataImage';
  url: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type SiteDataNetworks = {
  __typename?: 'SiteDataNetworks';
  url: Scalars['String']['output'];
  title: Scalars['String']['output'];
  icon: Scalars['String']['output'];
};

export type SiteData = Node & Document & {
  __typename?: 'SiteData';
  _warning?: Maybe<Scalars['String']['output']>;
  _seo?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  titleTemplate?: Maybe<Scalars['String']['output']>;
  twitterUsername?: Maybe<Scalars['String']['output']>;
  fbPageUrl?: Maybe<Scalars['String']['output']>;
  image?: Maybe<SiteDataImage>;
  _footer?: Maybe<Scalars['String']['output']>;
  informations?: Maybe<Scalars['JSON']['output']>;
  networks?: Maybe<Array<Maybe<SiteDataNetworks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteDataImageFilter = {
  url?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type SiteDataNetworksFilter = {
  url?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type SiteDataFilter = {
  _warning?: InputMaybe<StringFilter>;
  _seo?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  titleTemplate?: InputMaybe<StringFilter>;
  twitterUsername?: InputMaybe<StringFilter>;
  fbPageUrl?: InputMaybe<StringFilter>;
  image?: InputMaybe<SiteDataImageFilter>;
  _footer?: InputMaybe<StringFilter>;
  informations?: InputMaybe<RichTextFilter>;
  networks?: InputMaybe<SiteDataNetworksFilter>;
};

export type SiteDataConnectionEdges = {
  __typename?: 'SiteDataConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteData>;
};

export type SiteDataConnection = Connection & {
  __typename?: 'SiteDataConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteDataConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateHomeData: HomeData;
  createHomeData: HomeData;
  updateTeam: Team;
  createTeam: Team;
  updateAssociate: Associate;
  createAssociate: Associate;
  updatePage: Page;
  createPage: Page;
  updateNavDataPrimary: NavDataPrimary;
  createNavDataPrimary: NavDataPrimary;
  updateNavDataSecondary: NavDataSecondary;
  createNavDataSecondary: NavDataSecondary;
  updateSiteData: SiteData;
  createSiteData: SiteData;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationUpdateHomeDataArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeDataMutation;
};


export type MutationCreateHomeDataArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeDataMutation;
};


export type MutationUpdateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationCreateTeamArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMutation;
};


export type MutationUpdateAssociateArgs = {
  relativePath: Scalars['String']['input'];
  params: AssociateMutation;
};


export type MutationCreateAssociateArgs = {
  relativePath: Scalars['String']['input'];
  params: AssociateMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateNavDataPrimaryArgs = {
  relativePath: Scalars['String']['input'];
  params: NavDataPrimaryMutation;
};


export type MutationCreateNavDataPrimaryArgs = {
  relativePath: Scalars['String']['input'];
  params: NavDataPrimaryMutation;
};


export type MutationUpdateNavDataSecondaryArgs = {
  relativePath: Scalars['String']['input'];
  params: NavDataSecondaryMutation;
};


export type MutationCreateNavDataSecondaryArgs = {
  relativePath: Scalars['String']['input'];
  params: NavDataSecondaryMutation;
};


export type MutationUpdateSiteDataArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteDataMutation;
};


export type MutationCreateSiteDataArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteDataMutation;
};

export type DocumentUpdateMutation = {
  homeData?: InputMaybe<HomeDataMutation>;
  team?: InputMaybe<TeamMutation>;
  associate?: InputMaybe<AssociateMutation>;
  page?: InputMaybe<PageMutation>;
  navDataPrimary?: InputMaybe<NavDataPrimaryMutation>;
  navDataSecondary?: InputMaybe<NavDataSecondaryMutation>;
  siteData?: InputMaybe<SiteDataMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homeData?: InputMaybe<HomeDataMutation>;
  team?: InputMaybe<TeamMutation>;
  associate?: InputMaybe<AssociateMutation>;
  page?: InputMaybe<PageMutation>;
  navDataPrimary?: InputMaybe<NavDataPrimaryMutation>;
  navDataSecondary?: InputMaybe<NavDataSecondaryMutation>;
  siteData?: InputMaybe<SiteDataMutation>;
};

export type HomeDataOffresImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type HomeDataOffresMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  base_line?: InputMaybe<Scalars['String']['input']>;
  text?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<HomeDataOffresImageMutation>;
};

export type HomeDataPrincipe_ImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type HomeDataTestimonialMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type HomeDataGalleryMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type HomeDataMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  hero_text?: InputMaybe<Scalars['JSON']['input']>;
  intro_title?: InputMaybe<Scalars['String']['input']>;
  intro_text?: InputMaybe<Scalars['JSON']['input']>;
  intro_offre?: InputMaybe<Scalars['String']['input']>;
  offres?: InputMaybe<Array<InputMaybe<HomeDataOffresMutation>>>;
  principe_title?: InputMaybe<Scalars['String']['input']>;
  principe_sub_title?: InputMaybe<Scalars['JSON']['input']>;
  principe_text?: InputMaybe<Scalars['JSON']['input']>;
  principe_image?: InputMaybe<HomeDataPrincipe_ImageMutation>;
  principe_text_image?: InputMaybe<Scalars['JSON']['input']>;
  principe_text_bt_label?: InputMaybe<Scalars['String']['input']>;
  principe_text_bt_url?: InputMaybe<Scalars['String']['input']>;
  testimonial?: InputMaybe<Array<InputMaybe<HomeDataTestimonialMutation>>>;
  gallery?: InputMaybe<Array<InputMaybe<HomeDataGalleryMutation>>>;
};

export type TeamEquipeMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  hero_bg?: InputMaybe<Scalars['String']['input']>;
};

export type TeamContactMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  hero_bg?: InputMaybe<Scalars['String']['input']>;
  before_text?: InputMaybe<Scalars['String']['input']>;
  after_title?: InputMaybe<Scalars['String']['input']>;
  after_text?: InputMaybe<Scalars['String']['input']>;
};

export type TeamMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  education?: InputMaybe<Scalars['String']['input']>;
  citation?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['JSON']['input']>;
  image_inactive?: InputMaybe<Scalars['String']['input']>;
  image_active?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
};

export type TeamMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  _team?: InputMaybe<Scalars['String']['input']>;
  equipe?: InputMaybe<TeamEquipeMutation>;
  _contact?: InputMaybe<Scalars['String']['input']>;
  contact?: InputMaybe<TeamContactMutation>;
  members?: InputMaybe<Array<InputMaybe<TeamMembersMutation>>>;
};

export type AssociateAssociatesImageMutation = {
  src?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type AssociateAssociatesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  published?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  image?: InputMaybe<AssociateAssociatesImageMutation>;
};

export type AssociateMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  hero_bg?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['JSON']['input']>;
  associates?: InputMaybe<Array<InputMaybe<AssociateAssociatesMutation>>>;
};

export type PageMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  hero_bg?: InputMaybe<Scalars['String']['input']>;
  createdAt?: InputMaybe<Scalars['String']['input']>;
  updatedAt?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  useProse?: InputMaybe<Scalars['Boolean']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type NavDataPrimaryLinksChildrenMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  isButton?: InputMaybe<Scalars['Boolean']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
  target?: InputMaybe<Scalars['String']['input']>;
};

export type NavDataPrimaryLinksMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  isButton?: InputMaybe<Scalars['Boolean']['input']>;
  target?: InputMaybe<Scalars['String']['input']>;
  children?: InputMaybe<Array<InputMaybe<NavDataPrimaryLinksChildrenMutation>>>;
};

export type NavDataPrimaryMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<NavDataPrimaryLinksMutation>>>;
};

export type NavDataSecondaryLinksMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  isButton?: InputMaybe<Scalars['Boolean']['input']>;
  target?: InputMaybe<Scalars['String']['input']>;
};

export type NavDataSecondaryMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  links?: InputMaybe<Array<InputMaybe<NavDataSecondaryLinksMutation>>>;
};

export type SiteDataImageMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataNetworksMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataMutation = {
  _warning?: InputMaybe<Scalars['String']['input']>;
  _seo?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  titleTemplate?: InputMaybe<Scalars['String']['input']>;
  twitterUsername?: InputMaybe<Scalars['String']['input']>;
  fbPageUrl?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<SiteDataImageMutation>;
  _footer?: InputMaybe<Scalars['String']['input']>;
  informations?: InputMaybe<Scalars['JSON']['input']>;
  networks?: InputMaybe<Array<InputMaybe<SiteDataNetworksMutation>>>;
};

export type HomeDataPartsFragment = { __typename: 'HomeData', _warning?: string | null, hero_text?: any | null, intro_title?: string | null, intro_text?: any | null, intro_offre?: string | null, principe_title?: string | null, principe_sub_title?: any | null, principe_text?: any | null, principe_text_image?: any | null, principe_text_bt_label?: string | null, principe_text_bt_url?: string | null, offres?: Array<{ __typename: 'HomeDataOffres', title?: string | null, base_line?: string | null, text?: string | null, image?: { __typename: 'HomeDataOffresImage', src: string, alt: string } | null } | null> | null, principe_image?: { __typename: 'HomeDataPrincipe_image', src: string, alt: string } | null, testimonial?: Array<{ __typename: 'HomeDataTestimonial', text?: string | null, name?: string | null } | null> | null, gallery?: Array<{ __typename: 'HomeDataGallery', src: string, alt: string } | null> | null };

export type TeamPartsFragment = { __typename: 'Team', _warning?: string | null, _team?: string | null, _contact?: string | null, equipe?: { __typename: 'TeamEquipe', title: string, hero_bg: string } | null, contact?: { __typename: 'TeamContact', title: string, hero_bg: string, before_text?: string | null, after_title?: string | null, after_text?: string | null } | null, members?: Array<{ __typename: 'TeamMembers', name: string, published: boolean, role: string, education: string, citation: string, bio: any, image_inactive: string, image_active: string, linkedin?: string | null, email?: string | null } | null> | null };

export type AssociatePartsFragment = { __typename: 'Associate', _warning?: string | null, title: string, hero_bg: string, intro?: any | null, associates?: Array<{ __typename: 'AssociateAssociates', name: string, url?: string | null, published: boolean, description: any, image?: { __typename: 'AssociateAssociatesImage', src: string, alt: string } | null } | null> | null };

export type PagePartsFragment = { __typename: 'Page', _warning?: string | null, title: string, hero_bg: string, createdAt?: string | null, updatedAt?: string | null, description: string, useProse?: boolean | null, body?: any | null };

export type NavDataPrimaryPartsFragment = { __typename: 'NavDataPrimary', _warning?: string | null, links?: Array<{ __typename: 'NavDataPrimaryLinks', name: string, path: string, title: string, isButton: boolean, target: string, children?: Array<{ __typename: 'NavDataPrimaryLinksChildren', name: string, title: string, isButton: boolean, path: string, target: string } | null> | null } | null> | null };

export type NavDataSecondaryPartsFragment = { __typename: 'NavDataSecondary', _warning?: string | null, links?: Array<{ __typename: 'NavDataSecondaryLinks', name: string, path: string, title: string, isButton: boolean, target: string } | null> | null };

export type SiteDataPartsFragment = { __typename: 'SiteData', _warning?: string | null, _seo?: string | null, title: string, description?: string | null, titleTemplate?: string | null, twitterUsername?: string | null, fbPageUrl?: string | null, _footer?: string | null, informations?: any | null, image?: { __typename: 'SiteDataImage', url: string, alt: string } | null, networks?: Array<{ __typename: 'SiteDataNetworks', url: string, title: string, icon: string } | null> | null };

export type HomeDataQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeDataQuery = { __typename?: 'Query', homeData: { __typename: 'HomeData', id: string, _warning?: string | null, hero_text?: any | null, intro_title?: string | null, intro_text?: any | null, intro_offre?: string | null, principe_title?: string | null, principe_sub_title?: any | null, principe_text?: any | null, principe_text_image?: any | null, principe_text_bt_label?: string | null, principe_text_bt_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, offres?: Array<{ __typename: 'HomeDataOffres', title?: string | null, base_line?: string | null, text?: string | null, image?: { __typename: 'HomeDataOffresImage', src: string, alt: string } | null } | null> | null, principe_image?: { __typename: 'HomeDataPrincipe_image', src: string, alt: string } | null, testimonial?: Array<{ __typename: 'HomeDataTestimonial', text?: string | null, name?: string | null } | null> | null, gallery?: Array<{ __typename: 'HomeDataGallery', src: string, alt: string } | null> | null } };

export type HomeDataConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeDataFilter>;
}>;


export type HomeDataConnectionQuery = { __typename?: 'Query', homeDataConnection: { __typename?: 'HomeDataConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeDataConnectionEdges', cursor: string, node?: { __typename: 'HomeData', id: string, _warning?: string | null, hero_text?: any | null, intro_title?: string | null, intro_text?: any | null, intro_offre?: string | null, principe_title?: string | null, principe_sub_title?: any | null, principe_text?: any | null, principe_text_image?: any | null, principe_text_bt_label?: string | null, principe_text_bt_url?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, offres?: Array<{ __typename: 'HomeDataOffres', title?: string | null, base_line?: string | null, text?: string | null, image?: { __typename: 'HomeDataOffresImage', src: string, alt: string } | null } | null> | null, principe_image?: { __typename: 'HomeDataPrincipe_image', src: string, alt: string } | null, testimonial?: Array<{ __typename: 'HomeDataTestimonial', text?: string | null, name?: string | null } | null> | null, gallery?: Array<{ __typename: 'HomeDataGallery', src: string, alt: string } | null> | null } | null } | null> | null } };

export type TeamQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamQuery = { __typename?: 'Query', team: { __typename: 'Team', id: string, _warning?: string | null, _team?: string | null, _contact?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, equipe?: { __typename: 'TeamEquipe', title: string, hero_bg: string } | null, contact?: { __typename: 'TeamContact', title: string, hero_bg: string, before_text?: string | null, after_title?: string | null, after_text?: string | null } | null, members?: Array<{ __typename: 'TeamMembers', name: string, published: boolean, role: string, education: string, citation: string, bio: any, image_inactive: string, image_active: string, linkedin?: string | null, email?: string | null } | null> | null } };

export type TeamConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamFilter>;
}>;


export type TeamConnectionQuery = { __typename?: 'Query', teamConnection: { __typename?: 'TeamConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamConnectionEdges', cursor: string, node?: { __typename: 'Team', id: string, _warning?: string | null, _team?: string | null, _contact?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, equipe?: { __typename: 'TeamEquipe', title: string, hero_bg: string } | null, contact?: { __typename: 'TeamContact', title: string, hero_bg: string, before_text?: string | null, after_title?: string | null, after_text?: string | null } | null, members?: Array<{ __typename: 'TeamMembers', name: string, published: boolean, role: string, education: string, citation: string, bio: any, image_inactive: string, image_active: string, linkedin?: string | null, email?: string | null } | null> | null } | null } | null> | null } };

export type AssociateQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AssociateQuery = { __typename?: 'Query', associate: { __typename: 'Associate', id: string, _warning?: string | null, title: string, hero_bg: string, intro?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, associates?: Array<{ __typename: 'AssociateAssociates', name: string, url?: string | null, published: boolean, description: any, image?: { __typename: 'AssociateAssociatesImage', src: string, alt: string } | null } | null> | null } };

export type AssociateConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AssociateFilter>;
}>;


export type AssociateConnectionQuery = { __typename?: 'Query', associateConnection: { __typename?: 'AssociateConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AssociateConnectionEdges', cursor: string, node?: { __typename: 'Associate', id: string, _warning?: string | null, title: string, hero_bg: string, intro?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, associates?: Array<{ __typename: 'AssociateAssociates', name: string, url?: string | null, published: boolean, description: any, image?: { __typename: 'AssociateAssociatesImage', src: string, alt: string } | null } | null> | null } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, _warning?: string | null, title: string, hero_bg: string, createdAt?: string | null, updatedAt?: string | null, description: string, useProse?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, _warning?: string | null, title: string, hero_bg: string, createdAt?: string | null, updatedAt?: string | null, description: string, useProse?: boolean | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NavDataPrimaryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NavDataPrimaryQuery = { __typename?: 'Query', navDataPrimary: { __typename: 'NavDataPrimary', id: string, _warning?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavDataPrimaryLinks', name: string, path: string, title: string, isButton: boolean, target: string, children?: Array<{ __typename: 'NavDataPrimaryLinksChildren', name: string, title: string, isButton: boolean, path: string, target: string } | null> | null } | null> | null } };

export type NavDataPrimaryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavDataPrimaryFilter>;
}>;


export type NavDataPrimaryConnectionQuery = { __typename?: 'Query', navDataPrimaryConnection: { __typename?: 'NavDataPrimaryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavDataPrimaryConnectionEdges', cursor: string, node?: { __typename: 'NavDataPrimary', id: string, _warning?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavDataPrimaryLinks', name: string, path: string, title: string, isButton: boolean, target: string, children?: Array<{ __typename: 'NavDataPrimaryLinksChildren', name: string, title: string, isButton: boolean, path: string, target: string } | null> | null } | null> | null } | null } | null> | null } };

export type NavDataSecondaryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NavDataSecondaryQuery = { __typename?: 'Query', navDataSecondary: { __typename: 'NavDataSecondary', id: string, _warning?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavDataSecondaryLinks', name: string, path: string, title: string, isButton: boolean, target: string } | null> | null } };

export type NavDataSecondaryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavDataSecondaryFilter>;
}>;


export type NavDataSecondaryConnectionQuery = { __typename?: 'Query', navDataSecondaryConnection: { __typename?: 'NavDataSecondaryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavDataSecondaryConnectionEdges', cursor: string, node?: { __typename: 'NavDataSecondary', id: string, _warning?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavDataSecondaryLinks', name: string, path: string, title: string, isButton: boolean, target: string } | null> | null } | null } | null> | null } };

export type SiteDataQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteDataQuery = { __typename?: 'Query', siteData: { __typename: 'SiteData', id: string, _warning?: string | null, _seo?: string | null, title: string, description?: string | null, titleTemplate?: string | null, twitterUsername?: string | null, fbPageUrl?: string | null, _footer?: string | null, informations?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, image?: { __typename: 'SiteDataImage', url: string, alt: string } | null, networks?: Array<{ __typename: 'SiteDataNetworks', url: string, title: string, icon: string } | null> | null } };

export type SiteDataConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteDataFilter>;
}>;


export type SiteDataConnectionQuery = { __typename?: 'Query', siteDataConnection: { __typename?: 'SiteDataConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteDataConnectionEdges', cursor: string, node?: { __typename: 'SiteData', id: string, _warning?: string | null, _seo?: string | null, title: string, description?: string | null, titleTemplate?: string | null, twitterUsername?: string | null, fbPageUrl?: string | null, _footer?: string | null, informations?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, image?: { __typename: 'SiteDataImage', url: string, alt: string } | null, networks?: Array<{ __typename: 'SiteDataNetworks', url: string, title: string, icon: string } | null> | null } | null } | null> | null } };

export const HomeDataPartsFragmentDoc = gql`
    fragment HomeDataParts on HomeData {
  __typename
  _warning
  hero_text
  intro_title
  intro_text
  intro_offre
  offres {
    __typename
    title
    base_line
    text
    image {
      __typename
      src
      alt
    }
  }
  principe_title
  principe_sub_title
  principe_text
  principe_image {
    __typename
    src
    alt
  }
  principe_text_image
  principe_text_bt_label
  principe_text_bt_url
  testimonial {
    __typename
    text
    name
  }
  gallery {
    __typename
    src
    alt
  }
}
    `;
export const TeamPartsFragmentDoc = gql`
    fragment TeamParts on Team {
  __typename
  _warning
  _team
  equipe {
    __typename
    title
    hero_bg
  }
  _contact
  contact {
    __typename
    title
    hero_bg
    before_text
    after_title
    after_text
  }
  members {
    __typename
    name
    published
    role
    education
    citation
    bio
    image_inactive
    image_active
    linkedin
    email
  }
}
    `;
export const AssociatePartsFragmentDoc = gql`
    fragment AssociateParts on Associate {
  __typename
  _warning
  title
  hero_bg
  intro
  associates {
    __typename
    name
    url
    published
    description
    image {
      __typename
      src
      alt
    }
  }
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  _warning
  title
  hero_bg
  createdAt
  updatedAt
  description
  useProse
  body
}
    `;
export const NavDataPrimaryPartsFragmentDoc = gql`
    fragment NavDataPrimaryParts on NavDataPrimary {
  __typename
  _warning
  links {
    __typename
    name
    path
    title
    isButton
    target
    children {
      __typename
      name
      title
      isButton
      path
      target
    }
  }
}
    `;
export const NavDataSecondaryPartsFragmentDoc = gql`
    fragment NavDataSecondaryParts on NavDataSecondary {
  __typename
  _warning
  links {
    __typename
    name
    path
    title
    isButton
    target
  }
}
    `;
export const SiteDataPartsFragmentDoc = gql`
    fragment SiteDataParts on SiteData {
  __typename
  _warning
  _seo
  title
  description
  titleTemplate
  twitterUsername
  fbPageUrl
  image {
    __typename
    url
    alt
  }
  _footer
  informations
  networks {
    __typename
    url
    title
    icon
  }
}
    `;
export const HomeDataDocument = gql`
    query homeData($relativePath: String!) {
  homeData(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeDataParts
  }
}
    ${HomeDataPartsFragmentDoc}`;
export const HomeDataConnectionDocument = gql`
    query homeDataConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeDataFilter) {
  homeDataConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeDataParts
      }
    }
  }
}
    ${HomeDataPartsFragmentDoc}`;
export const TeamDocument = gql`
    query team($relativePath: String!) {
  team(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamParts
  }
}
    ${TeamPartsFragmentDoc}`;
export const TeamConnectionDocument = gql`
    query teamConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamFilter) {
  teamConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamParts
      }
    }
  }
}
    ${TeamPartsFragmentDoc}`;
export const AssociateDocument = gql`
    query associate($relativePath: String!) {
  associate(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AssociateParts
  }
}
    ${AssociatePartsFragmentDoc}`;
export const AssociateConnectionDocument = gql`
    query associateConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AssociateFilter) {
  associateConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AssociateParts
      }
    }
  }
}
    ${AssociatePartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const NavDataPrimaryDocument = gql`
    query navDataPrimary($relativePath: String!) {
  navDataPrimary(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavDataPrimaryParts
  }
}
    ${NavDataPrimaryPartsFragmentDoc}`;
export const NavDataPrimaryConnectionDocument = gql`
    query navDataPrimaryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavDataPrimaryFilter) {
  navDataPrimaryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavDataPrimaryParts
      }
    }
  }
}
    ${NavDataPrimaryPartsFragmentDoc}`;
export const NavDataSecondaryDocument = gql`
    query navDataSecondary($relativePath: String!) {
  navDataSecondary(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavDataSecondaryParts
  }
}
    ${NavDataSecondaryPartsFragmentDoc}`;
export const NavDataSecondaryConnectionDocument = gql`
    query navDataSecondaryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavDataSecondaryFilter) {
  navDataSecondaryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavDataSecondaryParts
      }
    }
  }
}
    ${NavDataSecondaryPartsFragmentDoc}`;
export const SiteDataDocument = gql`
    query siteData($relativePath: String!) {
  siteData(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteDataParts
  }
}
    ${SiteDataPartsFragmentDoc}`;
export const SiteDataConnectionDocument = gql`
    query siteDataConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteDataFilter) {
  siteDataConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteDataParts
      }
    }
  }
}
    ${SiteDataPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homeData(variables: HomeDataQueryVariables, options?: C): Promise<{data: HomeDataQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeDataQueryVariables, query: string}> {
        return requester<{data: HomeDataQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeDataQueryVariables, query: string}, HomeDataQueryVariables>(HomeDataDocument, variables, options);
      },
    homeDataConnection(variables?: HomeDataConnectionQueryVariables, options?: C): Promise<{data: HomeDataConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeDataConnectionQueryVariables, query: string}> {
        return requester<{data: HomeDataConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeDataConnectionQueryVariables, query: string}, HomeDataConnectionQueryVariables>(HomeDataConnectionDocument, variables, options);
      },
    team(variables: TeamQueryVariables, options?: C): Promise<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}> {
        return requester<{data: TeamQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamQueryVariables, query: string}, TeamQueryVariables>(TeamDocument, variables, options);
      },
    teamConnection(variables?: TeamConnectionQueryVariables, options?: C): Promise<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}> {
        return requester<{data: TeamConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamConnectionQueryVariables, query: string}, TeamConnectionQueryVariables>(TeamConnectionDocument, variables, options);
      },
    associate(variables: AssociateQueryVariables, options?: C): Promise<{data: AssociateQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AssociateQueryVariables, query: string}> {
        return requester<{data: AssociateQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AssociateQueryVariables, query: string}, AssociateQueryVariables>(AssociateDocument, variables, options);
      },
    associateConnection(variables?: AssociateConnectionQueryVariables, options?: C): Promise<{data: AssociateConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AssociateConnectionQueryVariables, query: string}> {
        return requester<{data: AssociateConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AssociateConnectionQueryVariables, query: string}, AssociateConnectionQueryVariables>(AssociateConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    navDataPrimary(variables: NavDataPrimaryQueryVariables, options?: C): Promise<{data: NavDataPrimaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataPrimaryQueryVariables, query: string}> {
        return requester<{data: NavDataPrimaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataPrimaryQueryVariables, query: string}, NavDataPrimaryQueryVariables>(NavDataPrimaryDocument, variables, options);
      },
    navDataPrimaryConnection(variables?: NavDataPrimaryConnectionQueryVariables, options?: C): Promise<{data: NavDataPrimaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataPrimaryConnectionQueryVariables, query: string}> {
        return requester<{data: NavDataPrimaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataPrimaryConnectionQueryVariables, query: string}, NavDataPrimaryConnectionQueryVariables>(NavDataPrimaryConnectionDocument, variables, options);
      },
    navDataSecondary(variables: NavDataSecondaryQueryVariables, options?: C): Promise<{data: NavDataSecondaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataSecondaryQueryVariables, query: string}> {
        return requester<{data: NavDataSecondaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataSecondaryQueryVariables, query: string}, NavDataSecondaryQueryVariables>(NavDataSecondaryDocument, variables, options);
      },
    navDataSecondaryConnection(variables?: NavDataSecondaryConnectionQueryVariables, options?: C): Promise<{data: NavDataSecondaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataSecondaryConnectionQueryVariables, query: string}> {
        return requester<{data: NavDataSecondaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataSecondaryConnectionQueryVariables, query: string}, NavDataSecondaryConnectionQueryVariables>(NavDataSecondaryConnectionDocument, variables, options);
      },
    siteData(variables: SiteDataQueryVariables, options?: C): Promise<{data: SiteDataQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataQueryVariables, query: string}> {
        return requester<{data: SiteDataQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataQueryVariables, query: string}, SiteDataQueryVariables>(SiteDataDocument, variables, options);
      },
    siteDataConnection(variables?: SiteDataConnectionQueryVariables, options?: C): Promise<{data: SiteDataConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataConnectionQueryVariables, query: string}> {
        return requester<{data: SiteDataConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataConnectionQueryVariables, query: string}, SiteDataConnectionQueryVariables>(SiteDataConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
  options?: { branch?: string }
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: { branch?: string },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    })

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
  options?: {
    branch?: string
  }
) => {
  const requester = generateRequester(client, options)
  return getSdk(requester)
}

  