//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  navDataPrimary: NavDataPrimary;
  navDataPrimaryConnection: NavDataPrimaryConnection;
  navDataSecondary: NavDataSecondary;
  navDataSecondaryConnection: NavDataSecondaryConnection;
  siteData: SiteData;
  siteDataConnection: SiteDataConnection;
  page: Page;
  pageConnection: PageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavDataPrimaryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavDataPrimaryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavDataPrimaryFilter>;
};


export type QueryNavDataSecondaryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNavDataSecondaryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavDataSecondaryFilter>;
};


export type QuerySiteDataArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteDataConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteDataFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};

export type DocumentFilter = {
  navDataPrimary?: InputMaybe<NavDataPrimaryFilter>;
  navDataSecondary?: InputMaybe<NavDataSecondaryFilter>;
  siteData?: InputMaybe<SiteDataFilter>;
  page?: InputMaybe<PageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = NavDataPrimary | NavDataSecondary | SiteData | Page | Folder;

export type NavDataPrimaryLinksChildren = {
  __typename?: 'NavDataPrimaryLinksChildren';
  name: Scalars['String']['output'];
  title: Scalars['String']['output'];
  isButton: Scalars['Boolean']['output'];
  path: Scalars['String']['output'];
  target: Scalars['String']['output'];
};

export type NavDataPrimaryLinks = {
  __typename?: 'NavDataPrimaryLinks';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
  title: Scalars['String']['output'];
  isButton: Scalars['Boolean']['output'];
  target: Scalars['String']['output'];
  children?: Maybe<Array<Maybe<NavDataPrimaryLinksChildren>>>;
};

export type NavDataPrimary = Node & Document & {
  __typename?: 'NavDataPrimary';
  links?: Maybe<Array<Maybe<NavDataPrimaryLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NavDataPrimaryLinksChildrenFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  isButton?: InputMaybe<BooleanFilter>;
  path?: InputMaybe<StringFilter>;
  target?: InputMaybe<StringFilter>;
};

export type NavDataPrimaryLinksFilter = {
  name?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  isButton?: InputMaybe<BooleanFilter>;
  target?: InputMaybe<StringFilter>;
  children?: InputMaybe<NavDataPrimaryLinksChildrenFilter>;
};

export type NavDataPrimaryFilter = {
  links?: InputMaybe<NavDataPrimaryLinksFilter>;
};

export type NavDataPrimaryConnectionEdges = {
  __typename?: 'NavDataPrimaryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<NavDataPrimary>;
};

export type NavDataPrimaryConnection = Connection & {
  __typename?: 'NavDataPrimaryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NavDataPrimaryConnectionEdges>>>;
};

export type NavDataSecondaryLinks = {
  __typename?: 'NavDataSecondaryLinks';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
  title: Scalars['String']['output'];
  isButton: Scalars['Boolean']['output'];
  target: Scalars['String']['output'];
};

export type NavDataSecondary = Node & Document & {
  __typename?: 'NavDataSecondary';
  links?: Maybe<Array<Maybe<NavDataSecondaryLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NavDataSecondaryLinksFilter = {
  name?: InputMaybe<StringFilter>;
  path?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  isButton?: InputMaybe<BooleanFilter>;
  target?: InputMaybe<StringFilter>;
};

export type NavDataSecondaryFilter = {
  links?: InputMaybe<NavDataSecondaryLinksFilter>;
};

export type NavDataSecondaryConnectionEdges = {
  __typename?: 'NavDataSecondaryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<NavDataSecondary>;
};

export type NavDataSecondaryConnection = Connection & {
  __typename?: 'NavDataSecondaryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NavDataSecondaryConnectionEdges>>>;
};

export type SiteDataImage = {
  __typename?: 'SiteDataImage';
  url: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type SiteDataNetworks = {
  __typename?: 'SiteDataNetworks';
  url: Scalars['String']['output'];
  title: Scalars['String']['output'];
  icon: Scalars['String']['output'];
};

export type SiteData = Node & Document & {
  __typename?: 'SiteData';
  title: Scalars['String']['output'];
  titleTemplate?: Maybe<Scalars['String']['output']>;
  twitterUsername?: Maybe<Scalars['String']['output']>;
  fbPageUrl?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<SiteDataImage>;
  informations?: Maybe<Scalars['JSON']['output']>;
  networks?: Maybe<Array<Maybe<SiteDataNetworks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteDataImageFilter = {
  url?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SiteDataNetworksFilter = {
  url?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type SiteDataFilter = {
  title?: InputMaybe<StringFilter>;
  titleTemplate?: InputMaybe<StringFilter>;
  twitterUsername?: InputMaybe<StringFilter>;
  fbPageUrl?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<SiteDataImageFilter>;
  informations?: InputMaybe<RichTextFilter>;
  networks?: InputMaybe<SiteDataNetworksFilter>;
};

export type SiteDataConnectionEdges = {
  __typename?: 'SiteDataConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteData>;
};

export type SiteDataConnection = Connection & {
  __typename?: 'SiteDataConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteDataConnectionEdges>>>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  createdAt?: Maybe<Scalars['String']['output']>;
  updatedAt?: Maybe<Scalars['String']['output']>;
  useProse?: Maybe<Scalars['Boolean']['output']>;
  description: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PageBodyPositionableImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  caption?: InputMaybe<StringFilter>;
  class?: InputMaybe<StringFilter>;
  position?: InputMaybe<StringFilter>;
  imgWidth?: InputMaybe<StringFilter>;
};

export type PageBodyFilter = {
  PositionableImage?: InputMaybe<PageBodyPositionableImageFilter>;
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  createdAt?: InputMaybe<DatetimeFilter>;
  updatedAt?: InputMaybe<DatetimeFilter>;
  useProse?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<PageBodyFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateNavDataPrimary: NavDataPrimary;
  createNavDataPrimary: NavDataPrimary;
  updateNavDataSecondary: NavDataSecondary;
  createNavDataSecondary: NavDataSecondary;
  updateSiteData: SiteData;
  createSiteData: SiteData;
  updatePage: Page;
  createPage: Page;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationUpdateNavDataPrimaryArgs = {
  relativePath: Scalars['String']['input'];
  params: NavDataPrimaryMutation;
};


export type MutationCreateNavDataPrimaryArgs = {
  relativePath: Scalars['String']['input'];
  params: NavDataPrimaryMutation;
};


export type MutationUpdateNavDataSecondaryArgs = {
  relativePath: Scalars['String']['input'];
  params: NavDataSecondaryMutation;
};


export type MutationCreateNavDataSecondaryArgs = {
  relativePath: Scalars['String']['input'];
  params: NavDataSecondaryMutation;
};


export type MutationUpdateSiteDataArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteDataMutation;
};


export type MutationCreateSiteDataArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteDataMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};

export type DocumentUpdateMutation = {
  navDataPrimary?: InputMaybe<NavDataPrimaryMutation>;
  navDataSecondary?: InputMaybe<NavDataSecondaryMutation>;
  siteData?: InputMaybe<SiteDataMutation>;
  page?: InputMaybe<PageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  navDataPrimary?: InputMaybe<NavDataPrimaryMutation>;
  navDataSecondary?: InputMaybe<NavDataSecondaryMutation>;
  siteData?: InputMaybe<SiteDataMutation>;
  page?: InputMaybe<PageMutation>;
};

export type NavDataPrimaryLinksChildrenMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  isButton?: InputMaybe<Scalars['Boolean']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
  target?: InputMaybe<Scalars['String']['input']>;
};

export type NavDataPrimaryLinksMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  isButton?: InputMaybe<Scalars['Boolean']['input']>;
  target?: InputMaybe<Scalars['String']['input']>;
  children?: InputMaybe<Array<InputMaybe<NavDataPrimaryLinksChildrenMutation>>>;
};

export type NavDataPrimaryMutation = {
  links?: InputMaybe<Array<InputMaybe<NavDataPrimaryLinksMutation>>>;
};

export type NavDataSecondaryLinksMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  path?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  isButton?: InputMaybe<Scalars['Boolean']['input']>;
  target?: InputMaybe<Scalars['String']['input']>;
};

export type NavDataSecondaryMutation = {
  links?: InputMaybe<Array<InputMaybe<NavDataSecondaryLinksMutation>>>;
};

export type SiteDataImageMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataNetworksMutation = {
  url?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type SiteDataMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  titleTemplate?: InputMaybe<Scalars['String']['input']>;
  twitterUsername?: InputMaybe<Scalars['String']['input']>;
  fbPageUrl?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<SiteDataImageMutation>;
  informations?: InputMaybe<Scalars['JSON']['input']>;
  networks?: InputMaybe<Array<InputMaybe<SiteDataNetworksMutation>>>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  createdAt?: InputMaybe<Scalars['String']['input']>;
  updatedAt?: InputMaybe<Scalars['String']['input']>;
  useProse?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type NavDataPrimaryPartsFragment = { __typename: 'NavDataPrimary', links?: Array<{ __typename: 'NavDataPrimaryLinks', name: string, path: string, title: string, isButton: boolean, target: string, children?: Array<{ __typename: 'NavDataPrimaryLinksChildren', name: string, title: string, isButton: boolean, path: string, target: string } | null> | null } | null> | null };

export type NavDataSecondaryPartsFragment = { __typename: 'NavDataSecondary', links?: Array<{ __typename: 'NavDataSecondaryLinks', name: string, path: string, title: string, isButton: boolean, target: string } | null> | null };

export type SiteDataPartsFragment = { __typename: 'SiteData', title: string, titleTemplate?: string | null, twitterUsername?: string | null, fbPageUrl?: string | null, description?: string | null, informations?: any | null, image?: { __typename: 'SiteDataImage', url: string, alt: string } | null, networks?: Array<{ __typename: 'SiteDataNetworks', url: string, title: string, icon: string } | null> | null };

export type PagePartsFragment = { __typename: 'Page', title: string, createdAt?: string | null, updatedAt?: string | null, useProse?: boolean | null, description: string, body?: any | null };

export type NavDataPrimaryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NavDataPrimaryQuery = { __typename?: 'Query', navDataPrimary: { __typename: 'NavDataPrimary', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavDataPrimaryLinks', name: string, path: string, title: string, isButton: boolean, target: string, children?: Array<{ __typename: 'NavDataPrimaryLinksChildren', name: string, title: string, isButton: boolean, path: string, target: string } | null> | null } | null> | null } };

export type NavDataPrimaryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavDataPrimaryFilter>;
}>;


export type NavDataPrimaryConnectionQuery = { __typename?: 'Query', navDataPrimaryConnection: { __typename?: 'NavDataPrimaryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavDataPrimaryConnectionEdges', cursor: string, node?: { __typename: 'NavDataPrimary', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavDataPrimaryLinks', name: string, path: string, title: string, isButton: boolean, target: string, children?: Array<{ __typename: 'NavDataPrimaryLinksChildren', name: string, title: string, isButton: boolean, path: string, target: string } | null> | null } | null> | null } | null } | null> | null } };

export type NavDataSecondaryQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NavDataSecondaryQuery = { __typename?: 'Query', navDataSecondary: { __typename: 'NavDataSecondary', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavDataSecondaryLinks', name: string, path: string, title: string, isButton: boolean, target: string } | null> | null } };

export type NavDataSecondaryConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NavDataSecondaryFilter>;
}>;


export type NavDataSecondaryConnectionQuery = { __typename?: 'Query', navDataSecondaryConnection: { __typename?: 'NavDataSecondaryConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavDataSecondaryConnectionEdges', cursor: string, node?: { __typename: 'NavDataSecondary', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, links?: Array<{ __typename: 'NavDataSecondaryLinks', name: string, path: string, title: string, isButton: boolean, target: string } | null> | null } | null } | null> | null } };

export type SiteDataQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteDataQuery = { __typename?: 'Query', siteData: { __typename: 'SiteData', id: string, title: string, titleTemplate?: string | null, twitterUsername?: string | null, fbPageUrl?: string | null, description?: string | null, informations?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, image?: { __typename: 'SiteDataImage', url: string, alt: string } | null, networks?: Array<{ __typename: 'SiteDataNetworks', url: string, title: string, icon: string } | null> | null } };

export type SiteDataConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteDataFilter>;
}>;


export type SiteDataConnectionQuery = { __typename?: 'Query', siteDataConnection: { __typename?: 'SiteDataConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteDataConnectionEdges', cursor: string, node?: { __typename: 'SiteData', id: string, title: string, titleTemplate?: string | null, twitterUsername?: string | null, fbPageUrl?: string | null, description?: string | null, informations?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, image?: { __typename: 'SiteDataImage', url: string, alt: string } | null, networks?: Array<{ __typename: 'SiteDataNetworks', url: string, title: string, icon: string } | null> | null } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, createdAt?: string | null, updatedAt?: string | null, useProse?: boolean | null, description: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, createdAt?: string | null, updatedAt?: string | null, useProse?: boolean | null, description: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const NavDataPrimaryPartsFragmentDoc = gql`
    fragment NavDataPrimaryParts on NavDataPrimary {
  __typename
  links {
    __typename
    name
    path
    title
    isButton
    target
    children {
      __typename
      name
      title
      isButton
      path
      target
    }
  }
}
    `;
export const NavDataSecondaryPartsFragmentDoc = gql`
    fragment NavDataSecondaryParts on NavDataSecondary {
  __typename
  links {
    __typename
    name
    path
    title
    isButton
    target
  }
}
    `;
export const SiteDataPartsFragmentDoc = gql`
    fragment SiteDataParts on SiteData {
  __typename
  title
  titleTemplate
  twitterUsername
  fbPageUrl
  description
  image {
    __typename
    url
    alt
  }
  informations
  networks {
    __typename
    url
    title
    icon
  }
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  createdAt
  updatedAt
  useProse
  description
  body
}
    `;
export const NavDataPrimaryDocument = gql`
    query navDataPrimary($relativePath: String!) {
  navDataPrimary(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavDataPrimaryParts
  }
}
    ${NavDataPrimaryPartsFragmentDoc}`;
export const NavDataPrimaryConnectionDocument = gql`
    query navDataPrimaryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavDataPrimaryFilter) {
  navDataPrimaryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavDataPrimaryParts
      }
    }
  }
}
    ${NavDataPrimaryPartsFragmentDoc}`;
export const NavDataSecondaryDocument = gql`
    query navDataSecondary($relativePath: String!) {
  navDataSecondary(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavDataSecondaryParts
  }
}
    ${NavDataSecondaryPartsFragmentDoc}`;
export const NavDataSecondaryConnectionDocument = gql`
    query navDataSecondaryConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavDataSecondaryFilter) {
  navDataSecondaryConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavDataSecondaryParts
      }
    }
  }
}
    ${NavDataSecondaryPartsFragmentDoc}`;
export const SiteDataDocument = gql`
    query siteData($relativePath: String!) {
  siteData(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteDataParts
  }
}
    ${SiteDataPartsFragmentDoc}`;
export const SiteDataConnectionDocument = gql`
    query siteDataConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteDataFilter) {
  siteDataConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteDataParts
      }
    }
  }
}
    ${SiteDataPartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      navDataPrimary(variables: NavDataPrimaryQueryVariables, options?: C): Promise<{data: NavDataPrimaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataPrimaryQueryVariables, query: string}> {
        return requester<{data: NavDataPrimaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataPrimaryQueryVariables, query: string}, NavDataPrimaryQueryVariables>(NavDataPrimaryDocument, variables, options);
      },
    navDataPrimaryConnection(variables?: NavDataPrimaryConnectionQueryVariables, options?: C): Promise<{data: NavDataPrimaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataPrimaryConnectionQueryVariables, query: string}> {
        return requester<{data: NavDataPrimaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataPrimaryConnectionQueryVariables, query: string}, NavDataPrimaryConnectionQueryVariables>(NavDataPrimaryConnectionDocument, variables, options);
      },
    navDataSecondary(variables: NavDataSecondaryQueryVariables, options?: C): Promise<{data: NavDataSecondaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataSecondaryQueryVariables, query: string}> {
        return requester<{data: NavDataSecondaryQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataSecondaryQueryVariables, query: string}, NavDataSecondaryQueryVariables>(NavDataSecondaryDocument, variables, options);
      },
    navDataSecondaryConnection(variables?: NavDataSecondaryConnectionQueryVariables, options?: C): Promise<{data: NavDataSecondaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataSecondaryConnectionQueryVariables, query: string}> {
        return requester<{data: NavDataSecondaryConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NavDataSecondaryConnectionQueryVariables, query: string}, NavDataSecondaryConnectionQueryVariables>(NavDataSecondaryConnectionDocument, variables, options);
      },
    siteData(variables: SiteDataQueryVariables, options?: C): Promise<{data: SiteDataQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataQueryVariables, query: string}> {
        return requester<{data: SiteDataQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataQueryVariables, query: string}, SiteDataQueryVariables>(SiteDataDocument, variables, options);
      },
    siteDataConnection(variables?: SiteDataConnectionQueryVariables, options?: C): Promise<{data: SiteDataConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataConnectionQueryVariables, query: string}> {
        return requester<{data: SiteDataConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteDataConnectionQueryVariables, query: string}, SiteDataConnectionQueryVariables>(SiteDataConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
  options?: { branch?: string }
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: { branch?: string },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    })

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
  options?: {
    branch?: string
  }
) => {
  const requester = generateRequester(client, options)
  return getSdk(requester)
}

  